"""phase 2 core schema

Revision ID: 0001
Revises:
Create Date: 2026-07-14 23:42:27.525259+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduler_state",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("last_tick_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduler_state")),
    )
    op.create_table(
        "source_locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("scan_root", sa.Text(), nullable=False),
        sa.Column("display_root", sa.Text(), nullable=False),
        sa.Column("path_style", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("external_generation_policy", sa.String(length=10), nullable=False),
        sa.Column("include_extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("exclude_globs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scan_interval_minutes", sa.BigInteger(), nullable=True),
        sa.Column("sentinel_id", sa.Text(), nullable=True),
        sa.Column("last_successful_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_locations")),
        sa.UniqueConstraint("name", name=op.f("uq_source_locations_name")),
    )
    op.create_table(
        "catalog_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_location_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("extension", sa.String(length=32), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("last_observed_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("last_observed_mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_location_id"],
            ["source_locations.id"],
            name=op.f("fk_catalog_entries_source_location_id_source_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_entries")),
        sa.UniqueConstraint(
            "source_location_id",
            "relative_path",
            name=op.f("uq_catalog_entries_source_location_id"),
        ),
    )
    op.create_index(
        "ix_catalog_entries_location_state",
        "catalog_entries",
        ["source_location_id", "state"],
        unique=False,
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.BigInteger(), nullable=False),
        sa.Column("source_location_id", sa.UUID(), nullable=True),
        sa.Column("catalog_entry_id", sa.UUID(), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.BigInteger(), nullable=False),
        sa.Column("max_attempts", sa.BigInteger(), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress_phase", sa.String(length=50), nullable=True),
        sa.Column("progress_current", sa.BigInteger(), nullable=True),
        sa.Column("progress_total", sa.BigInteger(), nullable=True),
        sa.Column("progress_unit", sa.String(length=50), nullable=True),
        sa.Column("progress_message", sa.String(length=500), nullable=True),
        sa.Column("progress_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_class", sa.String(length=30), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("error_details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_by", sa.String(length=100), nullable=True),
        sa.Column("retry_of_job_id", sa.UUID(), nullable=True),
        sa.Column("root_job_id", sa.UUID(), nullable=True),
        sa.Column("replacement_job_id", sa.UUID(), nullable=True),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("dedupe_key", sa.String(length=300), nullable=True),
        sa.Column("request_key", sa.String(length=128), nullable=True),
        sa.Column("last_event_sequence", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(status = 'running') = (lease_owner IS NOT NULL AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)",
            name=op.f("ck_ingestion_jobs_lease_only_while_running"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'cancelled', 'superseded')) = (finished_at IS NOT NULL)",
            name=op.f("ck_ingestion_jobs_finished_only_when_terminal"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'retry_wait') OR status IN ('succeeded', 'failed', 'cancelled', 'superseded')",
            name=op.f("ck_ingestion_jobs_status_known"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts >= 1",
            name=op.f("ck_ingestion_jobs_attempt_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["catalog_entries.id"],
            name=op.f("fk_ingestion_jobs_catalog_entry_id_catalog_entries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_ingestion_jobs_retry_of_job_id_ingestion_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_location_id"],
            ["source_locations.id"],
            name=op.f("fk_ingestion_jobs_source_location_id_source_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
    )
    op.create_index(
        "ix_ingestion_jobs_claim_order",
        "ingestion_jobs",
        ["status", "available_at", "priority", "requested_at"],
        unique=False,
    )
    op.create_index(
        "one_open_job_per_dedupe_key",
        "ingestion_jobs",
        ["dedupe_key"],
        unique=True,
        postgresql_where=sa.text(
            "dedupe_key IS NOT NULL AND status IN ('queued', 'running', 'retry_wait')"
        ),
    )
    op.create_index(
        "one_open_manual_retry_per_job",
        "ingestion_jobs",
        ["retry_of_job_id"],
        unique=True,
        postgresql_where=sa.text(
            "origin = 'manual_retry' AND status IN ('queued', 'running', 'retry_wait')"
        ),
    )
    op.create_index(
        "one_open_scan_per_location",
        "ingestion_jobs",
        ["source_location_id"],
        unique=True,
        postgresql_where=sa.text(
            "job_type = 'scan_location' AND status IN ('queued', 'running', 'retry_wait')"
        ),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=500), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_idempotency_records_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("scope", name=op.f("uq_idempotency_records_scope")),
    )
    op.create_table(
        "ingestion_job_attempts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.BigInteger(), nullable=False),
        sa.Column("worker_id", sa.String(length=200), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=30), nullable=True),
        sa.Column("error_class", sa.String(length=30), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_ingestion_job_attempts_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_job_attempts")),
        sa.UniqueConstraint(
            "job_id", "attempt_number", name=op.f("uq_ingestion_job_attempts_job_id")
        ),
    )
    op.create_table(
        "job_checkpoints",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("checkpoint_name", sa.String(length=100), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_number", sa.BigInteger(), nullable=False),
        sa.Column("result_identity", sa.String(length=500), nullable=True),
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_job_checkpoints_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_checkpoints")),
        sa.UniqueConstraint(
            "job_id", "checkpoint_name", "input_fingerprint", name=op.f("uq_job_checkpoints_job_id")
        ),
    )
    op.create_table(
        "job_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("sequence_number", sa.BigInteger(), nullable=False),
        sa.Column("attempt_number", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_job_events_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint("job_id", "sequence_number", name=op.f("uq_job_events_job_id")),
    )
    op.create_table(
        "scan_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.BigInteger(), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("extension", sa.String(length=32), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "staged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_scan_observations_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_observations")),
        sa.UniqueConstraint(
            "job_id", "attempt_number", "relative_path", name=op.f("uq_scan_observations_job_id")
        ),
    )
    op.create_index(
        "ix_scan_observations_job_attempt",
        "scan_observations",
        ["job_id", "attempt_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scan_observations_job_attempt", table_name="scan_observations")
    op.drop_table("scan_observations")
    op.drop_table("job_events")
    op.drop_table("job_checkpoints")
    op.drop_table("ingestion_job_attempts")
    op.drop_table("idempotency_records")
    op.drop_index(
        "one_open_scan_per_location",
        table_name="ingestion_jobs",
        postgresql_where=sa.text(
            "job_type = 'scan_location' AND status IN ('queued', 'running', 'retry_wait')"
        ),
    )
    op.drop_index(
        "one_open_manual_retry_per_job",
        table_name="ingestion_jobs",
        postgresql_where=sa.text(
            "origin = 'manual_retry' AND status IN ('queued', 'running', 'retry_wait')"
        ),
    )
    op.drop_index(
        "one_open_job_per_dedupe_key",
        table_name="ingestion_jobs",
        postgresql_where=sa.text(
            "dedupe_key IS NOT NULL AND status IN ('queued', 'running', 'retry_wait')"
        ),
    )
    op.drop_index("ix_ingestion_jobs_claim_order", table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index("ix_catalog_entries_location_state", table_name="catalog_entries")
    op.drop_table("catalog_entries")
    op.drop_table("source_locations")
    op.drop_table("scheduler_state")
    # ### end Alembic commands ###
